language: python
python:
- '3.7'
script:
- nose2 -v
deploy:
  provider: pypi
  user: refaelkohen
  server: https://test.pypi.org/legacy/
  distributions: sdist bdist_wheel
  password:
    secure: spBv1+XjcZKn2SDwin5Ks7GzLcywJtYu0yUDE++MT79cANif37eG7+6uA+HTlYrBdmhX/Pgsw8zh7AzYtVVPFUhoqV+h8IzvRlPmlgGwRk0gnwf4uhMEU6SU41hmhYmrRoQlJRJEjNDfgMG7MXXX6G7yEiEdHIwydfndjI2VHxUJg2g4MpszQSTkl+tJuI3nt4o7gDXfkbbS5K+JdRwQZiNuhioKypgaHxvwC3d+bKORib5duTTl222QxChF4R6KJ/W7HoKMiCJ4794zAEax8m4GinReREn981PB0Z8q10y3b/lpocgiQNvEp8bztIZ+d1KiwGw4FXkrCNwV4yHm6nU4gghhZrO3nePrH3z20cRyrUqT/CRbFycypvnxQWwzKVLtbLFFpXcm5UWuCudPRZQR+0uibUu7K5cIIFm5Zx3Oz6gBYOdvxc1dqRAfNAdPR0NdvwQ7Nhw6sUcKThrPduk1kf66ZCaHjgxwn995nontkKv+BwFVYqjdP0XlwhJJh24d0QCB9UcZuNWZinpK7Wa7qKJsSFwzVCU1Lm1fWknTQo6Ke1fpxFJGHUQ9UrJSObXoKGs9eoUKoFD2WTizkpQMaFZo73UuNQjKkxzZ7ej5QliZM78y/LOZTmChQ+Hs417HDMP1zHfyzhgWlql1AWOTXnVjgduUhZ+oxE3oXII=
